parent_config: https://raw.githubusercontent.com/SPHTech/SPHSwiftlint/master/.swiftlint.yml

excluded:
- Pods
- Tests
- Demo
- .build
line_length:
    warning: 500
    error: 1000
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
conditional_returns_on_newline:
    if_only: true
empty_count:
    only_after_dot: false
large_tuple:
    warning: 4
    error: 6
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - lhs
    - rhs
    - i
    - j
    - k
    - id
    - x
    - y
    - ok
    - ad
    - zb
    - sm
    - wb
reporter: "xcode"